
server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: service
          uri: lb://SERVICE
          predicates:
            - Path=/service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/service/(?<segment>.*), /$\{segment}
        - id: service
          uri: lb://SERVICE
          predicates:
            - Path=/service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/service/(?<segment>.*), /$\{segment}
            
        - id: service2
          uri: lb://SERVICE2
          predicates:
            - Path=/service2/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/service2/(?<segment>.*), /$\{segment}
        - id: service2
          uri: lb://SERVICE2
          predicates:
            - Path=/service2/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/service2/(?<segment>.*), /$\{segment}
       





management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus
