
server:
  port: 8010


spring:
  application:
    name: service
  servlet:
    context-path: /svc1


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka

greeting:
  message: Hello-Hello


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
