
eureka:
  instance:
    prefer-ip-address: true
##    statusPageUrlPath: ${server.servletPath}/info
##    healthCheckUrlPath: ${server.servletPath}/health
  client:
    serviceUrl:
      defaultZone: http://localhost:108761/eureka  # default address
    register-with-eureka: true
  
#   service-b:
#     table:
#       max-threads: 27


spring:
  application:
    name: service-b
