server:
  port: 8181

spring:
  application:
    name: service-a
#
#eureka:
##  instance:
##    prefer-ip-address: true
##    statusPageUrlPath: ${server.servletPath}/info
##    healthCheckUrlPath: ${server.servletPath}/health
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka  # default address
#    register-with-eureka: true
##    fetchRegistry: true
##    registry-sync-retries: 5
##    healthcheck:
##      enabled: true






who:
  am:
    i: dev-service-a
