
server:
  port: 0


spring:
  application:
    name: service


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Hi


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans