server:
  port: 8765

spring:
  application:
    name: zuul

zuul:
  routes:
    serviceSimple:
      path: /service-a/simple/**
      serviceId: service-a
      stripPrefix: false
    serviceAdvanced:
      path: /service-a/advanced/**
      serviceId: service-a
      stripPrefix: false
  ratelimit:
    enabled: true
    repository: BUCKET4J_JCACHE
    behind-proxy: true
    add-response-headers: true
    deny-request:
      response-status-code: 404
    policy-list:
      serviceSimple:
        - limit: 10
          refresh-interval: 60
          type:
            - origin
      serviceAdvanced:
        - limit: 10
          refresh-interval: 2
          type:
            - origin
    strip-prefix: true

  ribbon:
    eager-load:
      enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 60000
  ribbonIsolationStrategy: THREAD
  treadpool:
    useSeparateThreadPools: true




eureka:
  instance:
    non-secure-port: ${server.port}
    preferIpAddress: true
  client:
    healthcheck: true
    register-with-eureka: true
    fetch-registry: true
    registry-sync-retries: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        sleepWindowMilliseconds: 5000
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
    service-a:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    service-b:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  dashboard:
    proxy-stream-allow-list: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        web: debug



service-a:
  ribbon:
    #    lisfOfServers: localhost:8181, localhost:8183
    eureka:
      enable: true
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    MaxAutoRetriesNextServer: 1

service-b:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    MaxAutoRetriesNextServer: 1
