spring:
  application:
    name: zuul

server:
  port: 8765

zuul:
#  routes:
#    service-a:
#      path: /first/**
#      url: http://localhost:8181  #수동등록
  ribbon:
    eager-load:
      enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 60000




eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetchRegistry: true
    registry-sync-retries: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        sleepWindowMilliseconds: 5000
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000

management:
  endpoints:
    web:
      exposure:
        include: info, routes, filters, refresh

logging:
  level:
    org:
      springframework:
        web: debug

