spring:
  application:
    name: zuul

server:
  port: 8765

zuul:
  routes:
    serviceSimple:
      path: /service-a/simple
      url: forward:/
    serviceAdvanced:
      path: /service-a/advanced
      url: forward:/
  ratelimit:
    enabled: true
    repository: BUCKET4J_JCACHE
    serviceSimple:
      service-a:
        - limit: 5
          refresh-interval: 60  # 5 requests / 60s
          type:
            - origin
      serviceAdvanced:
        - limit: 1
          refresh-interval: 2   # 1 request / 2s
          type:
            - origin
    strip-prefix: true
  ribbon:
    eager-load:
      enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 60000
    ribbonIsolationStrategy: THREAD
    treadpool:
      useSeparateThreadPools: true



eureka:
  instance:
    non-secure-port: ${server.port}
    preferIpAddress: true
  client:
    healthcheck: true
    register-with-eureka: true
    fetch-registry: true
    registry-sync-retries: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        sleepWindowMilliseconds: 5000
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
  dashboard:
    proxy-stream-allow-list: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        web: debug



service-a:
  ribbon:
#    lisfOfServers: localhost:8181, localhost:8183
    eureka:
      enable: true
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#      connect-timeout: 5000
#      ReadTimeout: 5000
#      MaxTotalHttpConnections: 500
#      MaxConnectionsPerHost: 100
