spring:
  application:
    name: zuul

server:
  port: 8765

zuul:
#  routes:
#    serviceSimple:
#      path: /service-a/simple
#      url: localhost:8765/service-a/simple
#    serviceAdvanced:
#      path: /service-a/advanced
#      url: localhost:8181/service-a/advanced
  ribbon:
    eager-load:
      enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 60000
  ribbonIsolationStrategy: THREAD
  treadpool:
    useSeparateThreadPools: true




eureka:
  instance:
    non-secure-port: ${server.port}
    preferIpAddress: true
  client:
    healthcheck: true
    register-with-eureka: true
    fetch-registry: true
    registry-sync-retries: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        sleepWindowMilliseconds: 5000
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
  dashboard:
    proxy-stream-allow-list: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org:
      springframework:
        web: debug

ratelimit:
  enabled: true
  repository: BUCKET4J_JCACHE
  policy-list:
    serviceSimple:
      - limit: 10
        refresh-interval: 60
        type:
          - origin
    serviceAdvanced:
      - limit: 10
        refresh-interval: 2
        type:
          - origin
  strip-prefix: true

service-a:
  ribbon:
#    lisfOfServers: localhost:8181, localhost:8183
    eureka:
      enable: true
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#      connect-timeout: 5000
#      ReadTimeout: 5000
#      MaxTotalHttpConnections: 500
#      MaxConnectionsPerHost: 100
